- name: Terraform Apply
  run: terraform apply -auto-approve \
    -var="image_tag=${{ github.sha }}" \
    -var="docker_username=${{ secrets.DOCKER_USERNAME }}" \
    -var="key_name=${{ secrets.AWS_KEY_NAME }}"
  working-directory: terraform
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


